//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicks.Yoga.Data.Search {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clicks.Yoga.Data.Search.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} IN (SELECT AccreditationBodyId FROM SearchRecordAccreditationBodyLink WHERE SearchRecordAccreditationBodyLink.RecordId = SearchRecord.Id).
        /// </summary>
        internal static string AccreditationBodyFilter {
            get {
                return ResourceManager.GetString("AccreditationBodyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string AndOperator {
            get {
                return ResourceManager.GetString("AndOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchRecord.Location.STWithin(geography::STPolyFromText({0}, {1})) = 1.
        /// </summary>
        internal static string BoundsFilter {
            get {
                return ResourceManager.GetString("BoundsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTAINS(SearchRecord.*, {0}).
        /// </summary>
        internal static string ContainsFilter {
            get {
                return ResourceManager.GetString("ContainsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchRecord.Date = {0}.
        /// </summary>
        internal static string DateFilter {
            get {
                return ResourceManager.GetString("DateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SearchRecord.Id DESC.
        /// </summary>
        internal static string DefaultOrder {
            get {
                return ResourceManager.GetString("DefaultOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchRecord.Location.STDistance(geography::STPointFromText(&apos;POINT ({0} {1})&apos;, {2})).
        /// </summary>
        internal static string DistanceExpression {
            get {
                return ResourceManager.GetString("DistanceExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchRecord.EntityTypeId IN ({0}).
        /// </summary>
        internal static string EntityTypeFilter {
            get {
                return ResourceManager.GetString("EntityTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COALESCE(Friendship.BlockedByFriend, 0) = 0.
        /// </summary>
        internal static string FriendshipBlockedFilter {
            get {
                return ResourceManager.GetString("FriendshipBlockedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM
        ///    SearchRecord
        ///    INNER JOIN EntityType ON SearchRecord.EntityTypeId = EntityType.Id
        ///    LEFT JOIN Image ON SearchRecord.ImageId = Image.Id
        ///    LEFT JOIN ImageType ON Image.TypeId = ImageType.Id
        ///    LEFT JOIN SearchRecord AS ParentSearchRecord ON SearchRecord.ParentId = ParentSearchRecord.Id
        ///    LEFT JOIN EntityType AS ParentEntityType ON ParentSearchRecord.EntityTypeId = ParentEntityType.Id
        ///    LEFT JOIN Image AS ParentImage ON ParentSearchRecord.ImageId = ParentImage.Id
        ///    LEFT JOIN Image [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FromClause {
            get {
                return ResourceManager.GetString("FromClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchRecord.Name.
        /// </summary>
        internal static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFSET {0} ROWS FETCH NEXT {1} ROWS ONLY.
        /// </summary>
        internal static string OffsetFetchClause {
            get {
                return ResourceManager.GetString("OffsetFetchClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY {0}.
        /// </summary>
        internal static string OrderByClause {
            get {
                return ResourceManager.GetString("OrderByClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;= {1}.
        /// </summary>
        internal static string RadiusFilter {
            get {
                return ResourceManager.GetString("RadiusFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    COUNT(*) OVER () AS TotalCount,
        ///    SearchRecord.EntityId AS EntityId,
        ///    EntityType.Name AS EntityTypeName,
        ///    EntityType.DisplayName as EntityTypeDisplayName,
        ///    EntityType.DisplayPlural as EntityTypeDisplayPlural,
        ///    EntityType.Controller as Controller,
        ///    SearchRecord.Name AS Name,
        ///    SearchRecord.Description AS Description,
        ///    SearchRecord.City AS City,
        ///    SearchRecord.Area AS Area,
        ///    SearchRecord.Country AS Country,
        ///    SearchRecord.Postcode AS Postcode,
        ///    SearchRec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectClause {
            get {
                return ResourceManager.GetString("SelectClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} IN (SELECT StyleId FROM SearchRecordStyleLink WHERE SearchRecordStyleLink.RecordId = SearchRecord.Id).
        /// </summary>
        internal static string StyleFilter {
            get {
                return ResourceManager.GetString("StyleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} IN (SELECT TeacherId FROM SearchRecordTeacherLink WHERE SearchRecordTeacherLink.RecordId = SearchRecord.Id).
        /// </summary>
        internal static string TeacherFilter {
            get {
                return ResourceManager.GetString("TeacherFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} IN (SELECT TeacherServiceId FROM SearchRecordTeacherServiceLink WHERE SearchRecordTeacherServiceLink.RecordId = SearchRecord.Id).
        /// </summary>
        internal static string TeacherServiceFilter {
            get {
                return ResourceManager.GetString("TeacherServiceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} IN (SELECT VenueId FROM SearchRecordVenueLink WHERE SearchRecordVenueLink.RecordId = SearchRecord.Id).
        /// </summary>
        internal static string VenueFilter {
            get {
                return ResourceManager.GetString("VenueFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} IN (SELECT VenueServiceId FROM SearchRecordVenueServiceLink WHERE SearchRecordVenueServiceLink.RecordId = SearchRecord.Id).
        /// </summary>
        internal static string VenueServiceFilter {
            get {
                return ResourceManager.GetString("VenueServiceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchRecord.VenueTypeId = {0}.
        /// </summary>
        internal static string VenueTypeFilter {
            get {
                return ResourceManager.GetString("VenueTypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE {0}.
        /// </summary>
        internal static string WhereClause {
            get {
                return ResourceManager.GetString("WhereClause", resourceCulture);
            }
        }
    }
}
