//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicks.Yoga.Portal.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clicks.Yoga.Portal.Resources.Errors.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an ability level..
        /// </summary>
        public static string AbilityLevelMissing {
            get {
                return ResourceManager.GetString("AbilityLevelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an address..
        /// </summary>
        public static string AddressEmpty {
            get {
                return ResourceManager.GetString("AddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the first line of your address..
        /// </summary>
        public static string AddressFirstLineEmpty {
            get {
                return ResourceManager.GetString("AddressFirstLineEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you not been born yet?.
        /// </summary>
        public static string BirthDateLessThanNow {
            get {
                return ResourceManager.GetString("BirthDateLessThanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your town or city..
        /// </summary>
        public static string CityEmpty {
            get {
                return ResourceManager.GetString("CityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country..
        /// </summary>
        public static string CountryNull {
            get {
                return ResourceManager.GetString("CountryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date you have selected is invalid..
        /// </summary>
        public static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description..
        /// </summary>
        public static string DescriptionEmpty {
            get {
                return ResourceManager.GetString("DescriptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a duration..
        /// </summary>
        public static string DurationEmpty {
            get {
                return ResourceManager.GetString("DurationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two addresses you have entered do not match..
        /// </summary>
        public static string EmailAddressConfirmationDifferent {
            get {
                return ResourceManager.GetString("EmailAddressConfirmationDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email address..
        /// </summary>
        public static string EmailAddressConfirmationEmpty {
            get {
                return ResourceManager.GetString("EmailAddressConfirmationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address..
        /// </summary>
        public static string EmailAddressEmpty {
            get {
                return ResourceManager.GetString("EmailAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string EmailAddressInvalid {
            get {
                return ResourceManager.GetString("EmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an end date..
        /// </summary>
        public static string FinishDateEmpty {
            get {
                return ResourceManager.GetString("FinishDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a forename..
        /// </summary>
        public static string ForenameEmpty {
            get {
                return ResourceManager.GetString("ForenameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a gender..
        /// </summary>
        public static string GenderMissing {
            get {
                return ResourceManager.GetString("GenderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you have uploaded is not a valid image..
        /// </summary>
        public static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location..
        /// </summary>
        public static string LocationMissing {
            get {
                return ResourceManager.GetString("LocationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name..
        /// </summary>
        public static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two passwords you have entered do not match..
        /// </summary>
        public static string PasswordConfirmationDifferent {
            get {
                return ResourceManager.GetString("PasswordConfirmationDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        public static string PasswordConfirmationEmpty {
            get {
                return ResourceManager.GetString("PasswordConfirmationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered is incorrect..
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password with more than 5 characters..
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string PasswordUnacceptable {
            get {
                return ResourceManager.GetString("PasswordUnacceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your post or zip code..
        /// </summary>
        public static string PostcodeEmpty {
            get {
                return ResourceManager.GetString("PostcodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the finish date is after the start date..
        /// </summary>
        public static string StartDateAfterFinishDate {
            get {
                return ResourceManager.GetString("StartDateAfterFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a start date..
        /// </summary>
        public static string StartDateEmpty {
            get {
                return ResourceManager.GetString("StartDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date must be in the future..
        /// </summary>
        public static string StartDateInFuture {
            get {
                return ResourceManager.GetString("StartDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a surname..
        /// </summary>
        public static string SurnameEmpty {
            get {
                return ResourceManager.GetString("SurnameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a teacher..
        /// </summary>
        public static string TeacherMissing {
            get {
                return ResourceManager.GetString("TeacherMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a phone number..
        /// </summary>
        public static string TelephoneEmpty {
            get {
                return ResourceManager.GetString("TelephoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms &amp; conditions..
        /// </summary>
        public static string TermsNotAccepted {
            get {
                return ResourceManager.GetString("TermsNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {MaxLength} characters or less..
        /// </summary>
        public static string TextTooLong {
            get {
                return ResourceManager.GetString("TextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid start and end time..
        /// </summary>
        public static string TimeRangeInvalid {
            get {
                return ResourceManager.GetString("TimeRangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a type..
        /// </summary>
        public static string TypeMissing {
            get {
                return ResourceManager.GetString("TypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid website address..
        /// </summary>
        public static string WebsiteInvalid {
            get {
                return ResourceManager.GetString("WebsiteInvalid", resourceCulture);
            }
        }
    }
}
