// <auto-generated />
namespace Clicks.Yoga.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FannableQuotesAndLingo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FannableQuotesAndLingo));
        
        string IMigrationMetadata.Id
        {
            get { return "201311181633528_FannableQuotesAndLingo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
