//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clicks.Yoga.Portal.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clicks.Yoga.Portal.Resources.Errors.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like there is already an account registered with this email address. Please login or change the email address to add your story..
        /// </summary>
        internal static string email_address_Taken_story {
            get {
                return ResourceManager.GetString("email_address_Taken_story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link has already been used..
        /// </summary>
        internal static string EmailAddressChangeRequestCompleted {
            get {
                return ResourceManager.GetString("EmailAddressChangeRequestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is another account using the email address you are trying to change to..
        /// </summary>
        internal static string EmailAddressChangeRequestDuplicate {
            get {
                return ResourceManager.GetString("EmailAddressChangeRequestDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link has now expired. Please try changing your email address again..
        /// </summary>
        internal static string EmailAddressChangeRequestExpired {
            get {
                return ResourceManager.GetString("EmailAddressChangeRequestExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the link you clicked. Please contact us for further information..
        /// </summary>
        internal static string EmailAddressChangeRequestUnknown {
            get {
                return ResourceManager.GetString("EmailAddressChangeRequestUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and click the confirmation link to complete changing your email address..
        /// </summary>
        internal static string EmailConfirmationRequired {
            get {
                return ResourceManager.GetString("EmailConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure you have entered your current password correctly..
        /// </summary>
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you have chosen does not meet the requirements..
        /// </summary>
        internal static string PasswordUnacceptable {
            get {
                return ResourceManager.GetString("PasswordUnacceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already another account with this email address..
        /// </summary>
        internal static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
    }
}
