// <auto-generated />
namespace Clicks.Yoga.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenameAccreditingBodies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameAccreditingBodies));
        
        string IMigrationMetadata.Id
        {
            get { return "201312181317222_RenameAccreditingBodies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
