// <auto-generated />
namespace Clicks.Yoga.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(info));
        
        string IMigrationMetadata.Id
        {
            get { return "201510122149001_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
